version : '2'

services :
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafka:
    build: ./kafka
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  server :
    build : ./server
    image : alternative-vote/server
    ports :
      - "3000:3000"
    volumes :
      - ./server/src:/usr/local/server/src
    depends_on:
      - kafka
  ui :
    build : ./ui
    image : alternative-vote/ui
    volumes:
      - ./ui/src:/usr/local/ui/src
    ports :
      - "8000:8000"
    depends_on:
      - server